# var: packages_to_update
#   - this var should contain a list of valid pakcage names you want to ensure are at latest release
---
- name: Update specified packages, defaults to all
  yum: name={{ item }} state=latest update_cache=yes
  with_items: "{{packages_to_update | default('*')}}"
  tags: packages
