# file: touch.yml
# var: paths_to_touch
#  - this var should contain a list of files or directories to touch
---
- name: Touch files or directories
  file: path={{ item }} state=touch
  with_items: paths_to_touch
