---
- name: Disable services starting at boot
  service: name={{ item }} enabled=no
  with_items: disable_services

- name: Restart server
  command: shutdown -r now "Ansible patching reboot"
  async: 0
  poll: 0
  ignore_errors: true
  tags: reboot

- name: Waiting for server to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ reboot_port | default(22) }}"
    delay: "{{ reboot_delay | default(30) }}"
    timeout: "{{ reboot_timeout | default(300) }}"
  sudo: false
  delegate_to: localhost
  tags: reboot
