# file: prereqs.yml
# Copyright 2016, Jonathan Kelley  
# License Apache Commons v2 
---

# Fix SSL InsecurePlatformWarning
- name: "Install openssl-devel"
  yum: name=openssl-devel state=latest

# Fix SSL InsecurePlatformWarning
- name: "Install libffi-devel"
  yum: name=libffi-devel state=latest

- name: "Setup tools"
  yum: name=python-setuptools state=latest

- name: "Install pip"
  shell: "easy_install pip"
